package Configuracion_reto2;
// Generated 21 ene 2025, 15:17:53 by Hibernate Tools 6.5.1.Final

/**
 * Cicloformativo generated by hbm2java
 */
public class Cicloformativo implements java.io.Serializable {

	private String idCiclo;
	private String nombre;

	public Cicloformativo() {
	}

	public Cicloformativo(String idCiclo, String nombre) {
		this.idCiclo = idCiclo;
		this.nombre = nombre;
	}

	public String getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(String idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
