package Configuracion_reto2;
// Generated 21 ene 2025, 15:17:53 by Hibernate Tools 6.5.1.Final

/**
 * Formacion generated by hbm2java
 */
public class Formacion implements java.io.Serializable {

	private FormacionId id;

	public Formacion() {
	}

	public Formacion(FormacionId id) {
		this.id = id;
	}

	public FormacionId getId() {
		return this.id;
	}

	public void setId(FormacionId id) {
		this.id = id;
	}

}
