package Configuracion_reto2;
// Generated 21 ene 2025, 15:17:53 by Hibernate Tools 6.5.1.Final

/**
 * Horario generated by hbm2java
 */
public class Horario implements java.io.Serializable {

	private Integer idHorario;
	private int hora;
	private String dia;
	private Integer aula;
	private String idAsignatura;

	public Horario() {
	}

	public Horario(int hora, String dia) {
		this.hora = hora;
		this.dia = dia;
	}

	public Horario(int hora, String dia, Integer aula, String idAsignatura) {
		this.hora = hora;
		this.dia = dia;
		this.aula = aula;
		this.idAsignatura = idAsignatura;
	}

	public Integer getIdHorario() {
		return this.idHorario;
	}

	public void setIdHorario(Integer idHorario) {
		this.idHorario = idHorario;
	}

	public int getHora() {
		return this.hora;
	}

	public void setHora(int hora) {
		this.hora = hora;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public Integer getAula() {
		return this.aula;
	}

	public void setAula(Integer aula) {
		this.aula = aula;
	}

	public String getIdAsignatura() {
		return this.idAsignatura;
	}

	public void setIdAsignatura(String idAsignatura) {
		this.idAsignatura = idAsignatura;
	}

}
